/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    projects: Project;
    'open-calls': OpenCall;
    registrations: Registration;
    'team-members': TeamMember;
    partners: Partner;
    pages: Page;
    'form-templates': FormTemplate;
    faqs: Faq;
    stories: Story;
    newsletters: Newsletter;
    'partner-applications': PartnerApplication;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'open-calls': OpenCallsSelect<false> | OpenCallsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'form-templates': FormTemplatesSelect<false> | FormTemplatesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    'partner-applications': PartnerApplicationsSelect<false> | PartnerApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'hy' | 'ru') | ('en' | 'hy' | 'ru')[];
  globals: {
    'email-settings': EmailSetting;
    'projects-settings': ProjectsSetting;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'email-settings': EmailSettingsSelect<false> | EmailSettingsSelect<true>;
    'projects-settings': ProjectsSettingsSelect<false> | ProjectsSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'hy' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _key?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  alt?: string | null;
  _key?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  /**
   * Set automatically from the start and end dates.
   */
  status?: ('ongoing' | 'completed' | 'upcoming') | null;
  fundingSource?: ('erasmus-plus' | 'other-eu' | 'national' | 'private') | null;
  /**
   * IC-YEC's role - leave blank if not applicable.
   */
  projectRole?: ('coordinator' | 'partner') | null;
  theme?: ('art' | 'sport' | 'emotional-intelligence' | 'training' | 'inclusion' | 'digital' | 'environment')[] | null;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Total number of participants in this project.
   */
  participants?: number | null;
  countries?:
    | {
        country?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Specific locations shown as pins on the interactive map.
   */
  mapPoints?:
    | {
        city: string;
        country: string;
        /**
         * Latitude (e.g. 40.1872)
         */
        lat: number;
        /**
         * Longitude (e.g. 44.5152)
         */
        lng: number;
        /**
         * Shown in the map tooltip.
         */
        description?: string | null;
        type?: ('main-venue' | 'partner-org' | 'event-location') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Key results and achievements of this project.
   */
  outcomes?:
    | {
        outcome: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Participant quotes shown on the project page.
   */
  testimonials?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        photo?: (number | null) | Media;
        country?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * YouTube or Vimeo URL for the project video.
   */
  videoUrl?: string | null;
  /**
   * Show on homepage featured section.
   */
  featured?: boolean | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Display order - set 1 to show first, 2 for second, etc. Leave blank to sort by date.
   */
  order?: number | null;
  partners?: (number | Partner)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  type: 'partner' | 'funder' | 'network' | 'official-representative';
  website?: string | null;
  logo?: (number | null) | Media;
  /**
   * e.g. "Official Armenian Representative" - shown as a badge on the About page.
   */
  representativeRole?: string | null;
  /**
   * Short paragraph shown in the affiliations section on the About page.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-calls".
 */
export interface OpenCall {
  id: number;
  title: string;
  slug: string;
  type: 'youth-exchange' | 'training-course' | 'esc-volunteering' | 'seminar' | 'other';
  deadline: string;
  status?: ('open' | 'closed' | 'archived') | null;
  location?: string | null;
  dates?: {
    from?: string | null;
    to?: string | null;
  };
  eligibility?: {
    ageMin?: number | null;
    ageMax?: number | null;
    countries?:
      | {
          country?: string | null;
          id?: string | null;
        }[]
      | null;
    spotsAvailable?: number | null;
  };
  coverImage?: (number | null) | Media;
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Dynamic form fields shown in the registration form. Add, reorder, or remove fields freely.
   */
  formFields?:
    | (
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            minLength?: number | null;
            maxLength?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            rows?: number | null;
            minLength?: number | null;
            maxLength?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textareaField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'emailField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            international?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'phoneField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            min?: number | null;
            max?: number | null;
            step?: number | null;
            /**
             * Label shown next to the input, e.g. "years"
             */
            unit?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            /**
             * Earliest selectable date
             */
            minDate?: string | null;
            /**
             * Latest selectable date
             */
            maxDate?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dateField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            /**
             * Allow selecting more than one option
             */
            multiple?: boolean | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'selectField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radioField';
          }
        | {
            /**
             * Checkbox label / agreement text
             */
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkboxField';
          }
        | {
            label: string;
            helpText?: string | null;
            /**
             * Require at least one selection
             */
            required?: boolean | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkboxGroupField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            /**
             * Comma-separated file extensions
             */
            accept?: string | null;
            maxSizeMB?: number | null;
            multiple?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fileField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'urlField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            multiple?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'countryField';
          }
        | {
            text: string;
            level?: ('h2' | 'h3' | 'h4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingField';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraphField';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'dividerField';
          }
      )[]
    | null;
  registrationEnabled?: boolean | null;
  /**
   * Pick a template to copy its fields into "Form Fields" on save. Clears automatically after applying.
   */
  applyTemplate?: (number | null) | FormTemplate;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-templates".
 */
export interface FormTemplate {
  id: number;
  /**
   * e.g. "Standard Youth Exchange", "ESC Volunteering"
   */
  name: string;
  /**
   * Optional note about when to use this template.
   */
  description?: string | null;
  /**
   * Build the field set once here. Apply it to any open call via the "Apply template" option.
   */
  formFields?:
    | (
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            minLength?: number | null;
            maxLength?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            rows?: number | null;
            minLength?: number | null;
            maxLength?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textareaField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'emailField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            international?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'phoneField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            min?: number | null;
            max?: number | null;
            step?: number | null;
            /**
             * Label shown next to the input, e.g. "years"
             */
            unit?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            /**
             * Earliest selectable date
             */
            minDate?: string | null;
            /**
             * Latest selectable date
             */
            maxDate?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dateField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            /**
             * Allow selecting more than one option
             */
            multiple?: boolean | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'selectField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radioField';
          }
        | {
            /**
             * Checkbox label / agreement text
             */
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkboxField';
          }
        | {
            label: string;
            helpText?: string | null;
            /**
             * Require at least one selection
             */
            required?: boolean | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkboxGroupField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            /**
             * Comma-separated file extensions
             */
            accept?: string | null;
            maxSizeMB?: number | null;
            multiple?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fileField';
          }
        | {
            label: string;
            placeholder?: string | null;
            helpText?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'urlField';
          }
        | {
            label: string;
            helpText?: string | null;
            required?: boolean | null;
            multiple?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'countryField';
          }
        | {
            text: string;
            level?: ('h2' | 'h3' | 'h4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingField';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraphField';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'dividerField';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  openCall: number | OpenCall;
  applicantName: string;
  email: string;
  phone?: string | null;
  country: string;
  dateOfBirth: string;
  motivationLetter?: string | null;
  cv?: (number | null) | Document;
  answers?:
    | {
        blockType?: string | null;
        fieldLabel?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('pending' | 'reviewing' | 'shortlisted' | 'interview' | 'accepted' | 'rejected') | null;
  /**
   * Google Form/Doc link - included in the acceptance email
   */
  agreementUrl?: string | null;
  /**
   * Internal notes - not visible to applicant
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  email?: string | null;
  linkedin?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Plain text answer. Use double line-breaks for paragraphs.
   */
  answer: string;
  category:
    | 'application-process'
    | 'erasmus-plus'
    | 'esc-volunteering'
    | 'youth-exchanges'
    | 'training-courses'
    | 'general';
  /**
   * Lower numbers appear first within a category.
   */
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  quote: string;
  author: string;
  /**
   * Age at time of participation
   */
  age?: number | null;
  country: string;
  /**
   * e.g. "Touch of the Art 2024"
   */
  projectName?: string | null;
  photo?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Lower = shown first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  title: string;
  slug: string;
  /**
   * e.g. "Spring 2024", "Issue #3"
   */
  issueName?: string | null;
  publishedDate: string;
  /**
   * Short summary shown in the archive preview (2–3 sentences).
   */
  preview: string;
  /**
   * Link to full newsletter (Mailchimp archive, PDF, etc.)
   */
  archiveUrl?: string | null;
  coverImage?: (number | null) | Media;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Organisations that have submitted a partnership request via the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-applications".
 */
export interface PartnerApplication {
  id: number;
  orgName: string;
  orgType: 'youth-ngo' | 'school' | 'youth-centre' | 'cultural' | 'municipality' | 'other';
  country: string;
  website?: string | null;
  contactName: string;
  email: string;
  contactRole?: string | null;
  projectInterests: ('youth-exchange' | 'training-course' | 'esc-volunteering' | 'seminar' | 'other')[];
  /**
   * Tell us about your organisation and what kind of collaboration you have in mind.
   */
  message: string;
  howHeard?: string | null;
  status: 'new' | 'reviewing' | 'contacted' | 'approved' | 'declined';
  /**
   * Only visible to admins.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'open-calls';
        value: number | OpenCall;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'form-templates';
        value: number | FormTemplate;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'partner-applications';
        value: number | PartnerApplication;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  fundingSource?: T;
  projectRole?: T;
  theme?: T;
  startDate?: T;
  endDate?: T;
  participants?: T;
  countries?:
    | T
    | {
        country?: T;
        id?: T;
      };
  mapPoints?:
    | T
    | {
        city?: T;
        country?: T;
        lat?: T;
        lng?: T;
        description?: T;
        type?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        outcome?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        photo?: T;
        country?: T;
        id?: T;
      };
  videoUrl?: T;
  featured?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  summary?: T;
  content?: T;
  order?: T;
  partners?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-calls_select".
 */
export interface OpenCallsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  deadline?: T;
  status?: T;
  location?: T;
  dates?:
    | T
    | {
        from?: T;
        to?: T;
      };
  eligibility?:
    | T
    | {
        ageMin?: T;
        ageMax?: T;
        countries?:
          | T
          | {
              country?: T;
              id?: T;
            };
        spotsAvailable?: T;
      };
  coverImage?: T;
  summary?: T;
  content?: T;
  formFields?:
    | T
    | {
        textField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              minLength?: T;
              maxLength?: T;
              id?: T;
              blockName?: T;
            };
        textareaField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              rows?: T;
              minLength?: T;
              maxLength?: T;
              id?: T;
              blockName?: T;
            };
        emailField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        phoneField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              international?: T;
              id?: T;
              blockName?: T;
            };
        numberField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              min?: T;
              max?: T;
              step?: T;
              unit?: T;
              id?: T;
              blockName?: T;
            };
        dateField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              minDate?: T;
              maxDate?: T;
              id?: T;
              blockName?: T;
            };
        selectField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              multiple?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        radioField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checkboxField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        checkboxGroupField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fileField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              accept?: T;
              maxSizeMB?: T;
              multiple?: T;
              id?: T;
              blockName?: T;
            };
        urlField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        countryField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              multiple?: T;
              id?: T;
              blockName?: T;
            };
        headingField?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        paragraphField?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        dividerField?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  registrationEnabled?: T;
  applyTemplate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  openCall?: T;
  applicantName?: T;
  email?: T;
  phone?: T;
  country?: T;
  dateOfBirth?: T;
  motivationLetter?: T;
  cv?: T;
  answers?:
    | T
    | {
        blockType?: T;
        fieldLabel?: T;
        value?: T;
        id?: T;
      };
  status?: T;
  agreementUrl?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  email?: T;
  linkedin?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  website?: T;
  logo?: T;
  representativeRole?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-templates_select".
 */
export interface FormTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  formFields?:
    | T
    | {
        textField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              minLength?: T;
              maxLength?: T;
              id?: T;
              blockName?: T;
            };
        textareaField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              rows?: T;
              minLength?: T;
              maxLength?: T;
              id?: T;
              blockName?: T;
            };
        emailField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        phoneField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              international?: T;
              id?: T;
              blockName?: T;
            };
        numberField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              min?: T;
              max?: T;
              step?: T;
              unit?: T;
              id?: T;
              blockName?: T;
            };
        dateField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              minDate?: T;
              maxDate?: T;
              id?: T;
              blockName?: T;
            };
        selectField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              multiple?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        radioField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checkboxField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        checkboxGroupField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fileField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              accept?: T;
              maxSizeMB?: T;
              multiple?: T;
              id?: T;
              blockName?: T;
            };
        urlField?:
          | T
          | {
              label?: T;
              placeholder?: T;
              helpText?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        countryField?:
          | T
          | {
              label?: T;
              helpText?: T;
              required?: T;
              multiple?: T;
              id?: T;
              blockName?: T;
            };
        headingField?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        paragraphField?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        dividerField?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  age?: T;
  country?: T;
  projectName?: T;
  photo?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  issueName?: T;
  publishedDate?: T;
  preview?: T;
  archiveUrl?: T;
  coverImage?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-applications_select".
 */
export interface PartnerApplicationsSelect<T extends boolean = true> {
  orgName?: T;
  orgType?: T;
  country?: T;
  website?: T;
  contactName?: T;
  email?: T;
  contactRole?: T;
  projectInterests?: T;
  message?: T;
  howHeard?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings".
 */
export interface EmailSetting {
  id: number;
  emailOnAccept?: boolean | null;
  /**
   * Off by default - staff choose manually per decision
   */
  emailOnReject?: boolean | null;
  emailOnWaitlist?: boolean | null;
  coordinatorEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-settings".
 */
export interface ProjectsSetting {
  id: number;
  mapSection?: {
    enabled?: boolean | null;
    title?: string | null;
    /**
     * Short description shown below the map title.
     */
    subtitle?: string | null;
    /**
     * Hex colour for countries that have projects (e.g. #3D3785).
     */
    activeCountryColor?: string | null;
    /**
     * Hex colour for location pins on the map.
     */
    pinColor?: string | null;
  };
  /**
   * Numbers shown in the stats bar above the map. Leave at 0 to hide.
   */
  impactStats?: {
    stats?:
      | {
          /**
           * e.g. "150+", "12", "5 years"
           */
          value: string;
          /**
           * e.g. "Participants", "Countries reached"
           */
          label: string;
          /**
           * Emoji or icon character (e.g. 🌍 👥 📋).
           */
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Contact details and social links shown in the footer and on the Contact page.
   */
  contact?: {
    /**
     * Main contact email (shown on the Contact page and in the footer).
     */
    email?: string | null;
    /**
     * Phone number, e.g. +374 00 000 000.
     */
    phone?: string | null;
    /**
     * Postal address shown on the Contact page.
     */
    address?: string | null;
    /**
     * Paste the full profile URL. Leave a field blank to hide that link.
     */
    social?: {
      /**
       * e.g. https://instagram.com/ic.yec
       */
      instagram?: string | null;
      /**
       * Full profile URL.
       */
      facebook?: string | null;
      /**
       * Full profile URL.
       */
      linkedin?: string | null;
      /**
       * Full channel URL.
       */
      youtube?: string | null;
      /**
       * Full profile URL.
       */
      tiktok?: string | null;
    };
  };
  /**
   * Footer tagline and navigation columns.
   */
  footer?: {
    /**
     * Short paragraph under the logo. Leave blank to use the default.
     */
    tagline?: string | null;
    /**
     * Footer navigation columns. Leave empty to use the built-in defaults.
     */
    columns?:
      | {
          heading: string;
          links?:
            | {
                label: string;
                /**
                 * Internal path (e.g. /about) or full URL.
                 */
                url: string;
                /**
                 * Open in a new tab.
                 */
                external?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  timeline?: {
    enabled?: boolean | null;
    title?: string | null;
    /**
     * Steps shown in the "after you apply" timeline.
     */
    steps?:
      | {
          /**
           * Emoji (e.g. 📝 🔍 ✉️ ✈️ 🎓)
           */
          icon?: string | null;
          title: string;
          description?: string | null;
          /**
           * e.g. "~2 weeks"
           */
          duration?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  erasmusExplainer?: {
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  partnerPortal?: {
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    /**
     * Direct URL to the Partner Information Form (PDF or Google Form).
     */
    pifUrl?: string | null;
    /**
     * Partnership inquiry email (pre-fills mailto link).
     */
    contactEmail?: string | null;
    /**
     * List the types of partnerships you offer.
     */
    types?:
      | {
          icon?: string | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * What IC-YEC requires from partner organisations.
     */
    requirements?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  newsletter?: {
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    /**
     * Mailchimp / Brevo / Google Form signup link.
     */
    signupUrl?: string | null;
    buttonLabel?: string | null;
    /**
     * Show last 3 newsletters below the signup form.
     */
    showArchive?: boolean | null;
  };
  badgeSettings?: {
    /**
     * Open calls closing within this many days show a pulsing urgency badge.
     */
    urgentDaysThreshold?: number | null;
    /**
     * Show a "● Live" badge on projects currently running.
     */
    showLiveBadge?: boolean | null;
  };
  /**
   * Configure the dark partner map shown on the home and projects pages.
   */
  mapConfig?: {
    /**
     * Hex color used to highlight partner countries on the map.
     */
    activeCountryColor?: string | null;
    /**
     * Hex color for the IC-YEC headquarters dot (home city).
     */
    homeCityColor?: string | null;
    /**
     * Hex color for partner city dots.
     */
    partnerCityColor?: string | null;
    /**
     * Hex color for countries without projects.
     */
    inactiveCountryColor?: string | null;
    /**
     * Hex background color behind the map.
     */
    backgroundColor?: string | null;
    /**
     * Legend label for highlighted countries.
     */
    legendActiveLabel?: string | null;
    /**
     * Legend label for the home city dot.
     */
    legendHomeLabel?: string | null;
    /**
     * Legend label for partner city dots.
     */
    legendCityLabel?: string | null;
    /**
     * Partner cities displayed as pulsing dots. Leave empty to use the built-in default list.
     */
    cities?:
      | {
          city: string;
          country: string;
          /**
           * Latitude (e.g. 40.18)
           */
          lat: number;
          /**
           * Longitude (e.g. 44.51)
           */
          lng: number;
          /**
           * Mark as IC-YEC HQ / home city
           */
          isHome?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * All editable text on the /about page.
   */
  aboutPage?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
    storyHeading?: string | null;
    storyParagraph1?: string | null;
    storyParagraph2?: string | null;
    /**
     * Key milestones shown in the "Our Story" section.
     */
    timeline?:
      | {
          year: string;
          label: string;
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
    missionBody?: string | null;
    visionBody?: string | null;
    valuesBody?: string | null;
    /**
     * Stats shown in the dark impact band.
     */
    pageStats?:
      | {
          value: string;
          label: string;
          icon?: string | null;
          /**
           * Small subtitle below the label
           */
          sub?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Steps in the "How we work" section.
     */
    howWeWork?:
      | {
          /**
           * Step number e.g. "01"
           */
          step: string;
          title: string;
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Focus area cards in the "What we work on" section.
     */
    focusAreas?:
      | {
          icon?: string | null;
          label: string;
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
    erasmusTitle?: string | null;
    erasmusBody?: string | null;
    /**
     * Show the "Our partners" section on the About page.
     */
    showPartnersSection?: boolean | null;
    ctaHeading?: string | null;
    ctaBody?: string | null;
    /**
     * Small pill above the hero heading.
     */
    heroBadge?: string | null;
    storyLabel?: string | null;
    /**
     * Third "Our story" paragraph. Leave blank to hide.
     */
    storyExtra?: string | null;
    missionVisionLabel?: string | null;
    missionVisionTitle?: string | null;
    missionHeading?: string | null;
    missionIcon?: string | null;
    visionHeading?: string | null;
    visionIcon?: string | null;
    valuesHeading?: string | null;
    valuesIcon?: string | null;
    impactLabel?: string | null;
    impactTitle?: string | null;
    howWeWorkLabel?: string | null;
    howWeWorkTitle?: string | null;
    focusAreasLabel?: string | null;
    focusAreasTitle?: string | null;
    erasmusBadge?: string | null;
    affiliationsLabel?: string | null;
    affiliationsTitle?: string | null;
    partnersLabel?: string | null;
    partnersTitle?: string | null;
    teamLabel?: string | null;
    teamTitle?: string | null;
    /**
     * Shown when no team members are published.
     */
    teamEmptyText?: string | null;
    ctaLabel?: string | null;
    /**
     * Pills shown in the hero. Leave empty for the built-in defaults.
     */
    heroStats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Benefit chips beside the Erasmus+ text. Leave empty for the built-in defaults.
     */
    erasmusBenefits?:
      | {
          icon?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Action cards in the final CTA section. Leave empty for the built-in defaults.
     */
    ctaCards?:
      | {
          icon?: string | null;
          title: string;
          desc?: string | null;
          /**
           * Internal path (e.g. /open-calls) or full URL.
           */
          href: string;
          linkLabel: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The "Who We Are" block shown on the homepage.
   */
  aboutSection?: {
    /**
     * Small label above the heading (e.g. "WHO WE ARE")
     */
    label?: string | null;
    heading?: string | null;
    intro?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
    /**
     * Focus area pills shown below the body text.
     */
    focusAreas?:
      | {
          /**
           * Emoji (e.g. 🎨 ⚽ 🌿)
           */
          icon?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Stat cards shown in the right column.
     */
    stats?:
      | {
          /**
           * e.g. "2018" or "500+"
           */
          value: string;
          /**
           * e.g. "Year founded"
           */
          label: string;
          /**
           * Emoji icon (e.g. 📅 🌍)
           */
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Per-theme breakdown shown on the Projects page. Leave blank to hide a theme.
   */
  themeImpact?: {
    themes?:
      | {
          theme: 'art' | 'sport' | 'emotional-intelligence' | 'training' | 'inclusion' | 'digital' | 'environment';
          /**
           * e.g. "12 projects"
           */
          projectCount?: string | null;
          /**
           * e.g. "200+ youth"
           */
          participantCount?: string | null;
          /**
           * e.g. "8 countries"
           */
          countriesCount?: string | null;
          /**
           * Emoji icon
           */
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  emailOnAccept?: T;
  emailOnReject?: T;
  emailOnWaitlist?: T;
  coordinatorEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-settings_select".
 */
export interface ProjectsSettingsSelect<T extends boolean = true> {
  mapSection?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        activeCountryColor?: T;
        pinColor?: T;
      };
  impactStats?:
    | T
    | {
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        social?:
          | T
          | {
              instagram?: T;
              facebook?: T;
              linkedin?: T;
              youtube?: T;
              tiktok?: T;
            };
      };
  footer?:
    | T
    | {
        tagline?: T;
        columns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    external?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  timeline?:
    | T
    | {
        enabled?: T;
        title?: T;
        steps?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              duration?: T;
              id?: T;
            };
      };
  erasmusExplainer?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  partnerPortal?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        pifUrl?: T;
        contactEmail?: T;
        types?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        requirements?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        signupUrl?: T;
        buttonLabel?: T;
        showArchive?: T;
      };
  badgeSettings?:
    | T
    | {
        urgentDaysThreshold?: T;
        showLiveBadge?: T;
      };
  mapConfig?:
    | T
    | {
        activeCountryColor?: T;
        homeCityColor?: T;
        partnerCityColor?: T;
        inactiveCountryColor?: T;
        backgroundColor?: T;
        legendActiveLabel?: T;
        legendHomeLabel?: T;
        legendCityLabel?: T;
        cities?:
          | T
          | {
              city?: T;
              country?: T;
              lat?: T;
              lng?: T;
              isHome?: T;
              id?: T;
            };
      };
  aboutPage?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
        storyHeading?: T;
        storyParagraph1?: T;
        storyParagraph2?: T;
        timeline?:
          | T
          | {
              year?: T;
              label?: T;
              desc?: T;
              id?: T;
            };
        missionBody?: T;
        visionBody?: T;
        valuesBody?: T;
        pageStats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              sub?: T;
              id?: T;
            };
        howWeWork?:
          | T
          | {
              step?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
        focusAreas?:
          | T
          | {
              icon?: T;
              label?: T;
              desc?: T;
              id?: T;
            };
        erasmusTitle?: T;
        erasmusBody?: T;
        showPartnersSection?: T;
        ctaHeading?: T;
        ctaBody?: T;
        heroBadge?: T;
        storyLabel?: T;
        storyExtra?: T;
        missionVisionLabel?: T;
        missionVisionTitle?: T;
        missionHeading?: T;
        missionIcon?: T;
        visionHeading?: T;
        visionIcon?: T;
        valuesHeading?: T;
        valuesIcon?: T;
        impactLabel?: T;
        impactTitle?: T;
        howWeWorkLabel?: T;
        howWeWorkTitle?: T;
        focusAreasLabel?: T;
        focusAreasTitle?: T;
        erasmusBadge?: T;
        affiliationsLabel?: T;
        affiliationsTitle?: T;
        partnersLabel?: T;
        partnersTitle?: T;
        teamLabel?: T;
        teamTitle?: T;
        teamEmptyText?: T;
        ctaLabel?: T;
        heroStats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        erasmusBenefits?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        ctaCards?:
          | T
          | {
              icon?: T;
              title?: T;
              desc?: T;
              href?: T;
              linkLabel?: T;
              id?: T;
            };
      };
  aboutSection?:
    | T
    | {
        label?: T;
        heading?: T;
        intro?: T;
        body?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        focusAreas?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  themeImpact?:
    | T
    | {
        themes?:
          | T
          | {
              theme?: T;
              projectCount?: T;
              participantCount?: T;
              countriesCount?: T;
              icon?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}